### ISSUE TITLE
[ISSUE]: FHDB 1.966 the CNF messes up the arrow indicators

### ISSUE THREAD

**Issue by Sel-en-ium** [israpps/FreeMcBoot-Installer#33]
### Checks

- [X] I have checked [__existing issues__](https://github.com/israpps/FreeMcBoot-Installer/issues) for duplicates and found none
- [X] I am using a build downloaded from [this repository](https://israpps.github.io/FreeMcBoot-Installer/test/8_Downloads.html)

### Describe the issue

You can see the arrows are a right arrow and some glitch instead of the up and down arrows they're supposed to be.

![PXL_20240713_002141378](https://github.com/user-attachments/assets/cde62772-91f2-46f4-8572-191133d67908)
![PXL_20240713_002612196](https://github.com/user-attachments/assets/468e1dd1-832f-4f7a-88ca-2615a3a08647)

### Console model

SCPH-39001

### Where do you have the issue?

FreeHdBoot

### Program version (if possible, also provide hash seen on installer used)

1.966

**Comment by israpps** [comment]
The stock config expects the HDDOSD charset order, that's why without it it looks like this

**Comment by Sel-en-ium** [comment]
Oh I see.  :o

I don't really know much about HDD-OSD 😅 
It sounds like it's an alternative to FHDB + OPL?  Is it included in the 1.966 install?  🤔

**Comment by Sel-en-ium** [comment]
(This is obviously very minor, so no worries if my questions aren't worthwhile, I'm just a bit curious. xD)

**Comment by israpps** [comment]
> Oh I see. :o
> 
> I don't really know much about HDD-OSD 😅 It sounds like it's an alternative to FHDB + OPL? Is it included in the 1.966 install? 🤔

HDD-OSD (aka: Browser 2.0 update) was an official $ony update that was installed on the HDD to enhance certain aspects of the browser, and support browsing the HDD and it's partitions.

FreeHdBoot manipulates the console menu to generate it's own menu, but on FreeHdBoot, you can put HDDOSD on a specific path along it's additional files and FreeHdBoot will use it instead of the console built-in menu to generate it's own menu, adapting it's features

**Comment by Sel-en-ium** [comment]
Ohh!  Cool! That's sick >:D
Thank you for the explanation! ♥️
